### DISCUSSION TITLE
Configuration for new install

### DISCUSSION THREAD

**Discussion by Midnitte** [hassio-addons/addon-ssh#526] [Q&A] [answered]
Hello!

I'm trying to set up this addon for the first time and perhaps am missing something basic, but based off the documentation, I was under the assumption that configuration of the addon took place within the Home Assistant `configuration.yaml`

> SSH add-on configuration:

```
log_level: info
ssh:
  username: homeassistant
  password: ""
  authorized_keys:
....
```
This results in an error when trying to reboot that "ssh" isn't a valid configuration option (despite the addon being installed).

The addon configuration tab itself has a message that there is no configuration to change:
![image](https://user-images.githubusercontent.com/49769850/229318965-ef14ae38-c27f-4c4c-a868-5e138b404637.png)

Is there something extremely basic I'm missing?
