### ISSUE TITLE
.sh-Files are not executed after Update

### ISSUE THREAD

**Issue by outrun0506** [hassio-addons/addon-ssh#113]
# Problem/Motivation
I have a Shell-Script to shutdown my NAS. After the last Addon update, this is not working anymore.

## Expected behavior
Shell-Script should be exexcuted.

## Actual behavior
Error Message in Log:

>[21:42:07] INFO: Received external command to execute:
>[21:42:07] INFO: > /config/shellscripts/nasoff.sh
>Our Cli:
>$ hassio help
>open terminal failed: not a terminal
>[21:42:07] ERROR: Command exited with a failure status.

Shell-Script I'm trying to run:
```
ssh -i /ssl/id_rsa root@***.***.***.*** shutdown -h now
```

WOL-Switch-Config from HA:

```yaml
- platform: wake_on_lan
  mac: "**-**-**-**-**-**"
  name: "NAS"
  host: ***.***.***.***
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: /config/shellscripts/nasoff.sh
```

If i run the Script from Terminal directly it works like a charm and my NAS is shutting down.

## Steps to reproduce
Run a Shell-Script from the Addon - but did not test it with a second one. I'm only using the above one.

Did I something wrong?

Thanks for helping 

BR
Lukas
