### ISSUE TITLE
Bind on port 22 issue

### ISSUE THREAD

**Issue by pr0fetul** [hassio-addons/addon-ssh#157]
# Problem/Motivation

Since the last version, I am receiving this error:
```
Bind to port 22 on 0.0.0.0 failed: Address in use.
Bind to port 22 on :: failed: Address in use.
```
HA 0.114.4
SSH addon version 7.5.0

Configuration:
```
ssh:
  username: hassio
  password: ************
  authorized_keys: []
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []
```

Running on Docker / Synology.
command  netstat -tulpn | grep 22 produces:
```
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      18712/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      18712/sshd
```
Any idea on why is the addon not working?

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
