### ISSUE TITLE
Cannot SSH in: syntax error in /etc/sudoers

### ISSUE THREAD

**Issue by paullessing** [hassio-addons/addon-ssh#170]
# Problem/Motivation

I'm trying to use the SSH addon. It used to work fine, but recently I have been unable to log in.

## Expected behavior

When I log in using `ssh -p 2222 localhost` from the same machine, or `ssh -p 2222 10.0.0.<x>` from another machine, I expect to be able to sign in and use SSH.

## Actual behavior

When I attempt to SSH in, I get the following error message:
```
 ssh -p 2222 10.0.0.<x>
>>> /etc/sudoers: syntax error near line 97 <<<
sudo: parse error in /etc/sudoers near line 97
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
Connection to 10.0.0.<x> closed.
```

**I can log in using the Web CLI from Home Assistant -> Supervisor -> SSH Plugin -> "Open Web CLI".

Looking at my `/etc/sudoers` file, line 97 is the last line:
```
#includedir /etc/sudoers.d
```

If I change the line to have a space after the `#`, things start working again - kind of:
```
# includedir /etc/sudoers.d
```
This allows me to log in, but I then get faced with the following screen:
```
 ssh -p 2222 10.0.0.<x>

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for <username>:
```
The user does not have a password, so I cannot log in (I am attempting to log in using a private key).

## Steps to reproduce

I am running:
* Supervisor 2020.12.2 using Docker 19.03.13 on a Raspberry Pi 4
* Home Assistant Core 0.118.0
* SSH & Web Terminal 7.8.0

My configuration:
```yaml
ssh:
  username: <username>
  password: ''
  authorized_keys:
    - >-
      ssh-rsa
      AAAAB3...Vdw==
      <username>@<host system>

      ssh-rsa
      AAAAB3...7Jr0N
      <username>@<remote machine>

      ssh-rsa
      AAAAB3...wEmbx
      <Username>@<local machine>

      ssh-rsa
      AAAAB3...GZw==
      <username>@<local machine>
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: false
share_sessions: false
packages: []
init_commands: []
```

Any help would be much appreciated.
