### ISSUE TITLE
this SSH will not accept any entries into the configuration.  when I select save, they go away. ?

### ISSUE THREAD

**Issue by kendurbin** [hassio-addons/addon-ssh#251]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
Then the validation by the supervisor is failing, perhaps you could share what you are trying to save?

**Comment by kendurbin** [comment]
![image](https://user-images.githubusercontent.com/57381759/116155413-ab65df80-a6af-11eb-9391-47b594df6f13.png)

**Comment by kendurbin** [comment]
when I select save, this all goes back to beginning.

**Comment by sinclairpaul** [comment]
Though you may not want to share the secrets :), its likely your key line, it need to be separated by a dash and space (YAML array/sequence)

e.g.:

```
ssh:
  username: hassio
  password: ''
  authorized_keys:
    - mykeyhere
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []
```
