### ISSUE TITLE
Troubleshoot agent forwarding (help wanted)

### ISSUE THREAD

**Issue by cmitz** [hassio-addons/addon-ssh#271]
# Problem/Motivation

I can't backup my config with Git because the SSH key is not forwarded correctly (I suspect).

Can someone help me figure out what part of my SSH config is wrong?

## Expected behavior

* `git push` would result in a succesful push
* `echo "$SSH_AUTH_SOCK"` would show _something_

## Actual behavior

* Permission denied when pushing commits
* Just whitespace when `echo "$SSH_AUTH_SOCK"` 

## Steps to reproduce

1. add `~/.ssh/id_rsa.pub` to `authorized_keys` in config
  1. And test if paswordless login works
2. `ssh-add ~/.id_rsa`
  1. -> `Identity added...`
  2. `ssh-add -L` should list the used key (or multiple if multiple keys are available)
3. `ssh -vvv -A casper@192.168.1.165 -i ~/.ssh/id_rsa` to login
4. `cd config && git push` -> "permission denied"

## Proposed changes

I don't really know

## Debug info

Add-on configuration:
```yaml
ssh:
  username: casper
  password: ''
  authorized_keys:
    - >-
      ssh-rsa
      AAAA...aw==
      [my email address]
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: true
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
```

`ssh -vvv -A casper@192.168.1.165 -i ~/.ssh/id_rsa` yielded:
```
...
debug1: Requesting authentication agent forwarding.
debug2: channel 0: request auth-agent-req@openssh.com confirm 0
debug3: send packet: type 98
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x48
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env TERM_SESSION_ID
debug3: Ignored env SSH_AUTH_SOCK
debug1: Sending env LC_TERMINAL_VERSION = 3.4.6
debug2: channel 0: request env confirm 0
...
```
