### ISSUE TITLE
mount commands doesnt work with hassio.addon_stdin

### ISSUE THREAD

**Issue by Electronlibre2012** [hassio-addons/addon-ssh#306]
# Problem/Motivation

>i mount a ssd disk with this command in the addon : 
```
docker container exec -it homeassistant /bin/bash
mount /dev/sdb1 /media/usbstorage
```
and it works as expected but i need to make after each reboot

## Expected behavior

> i read the doc and make an automation but it give an error : 
```
id: '1630252438502'
alias: Mount USB Storage SSD
description: ''
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: sudo docker container exec -i homeassistant /bin/bash
  - service: hassio.addon_stdin
    data:
      addon: a0d7b954_ssh
      input: sudo mount /dev/sdb1 /media/usbstorage
mode: single
```
## Actual behavior

[21:07:49] INFO: Received external command to execute:
[21:07:49] INFO: > sudo docker container exec -i homeassistant /bin/bash
/bin/bash: line 1: sudo mount /dev/sdb1 /media: No such file or directory

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Please, is someone can help a little...i learn...but i have a lot to learn ;)
