### ISSUE TITLE
SFTP no longer accepting RSA key

### ISSUE THREAD

**Issue by markmonroy** [hassio-addons/addon-ssh#354]
# Problem/Motivation

SFTP no longer accepting RSA key after 10.0.0 update

## Expected behavior

Expected SFTP to continue to work

## Actual behavior

SFTP stopped working

## Steps to reproduce

Update addon to 10.0.0, no config changes, SSH still works, but SFTP rejects my ssh-rsa key as "not in PubkeyAcceptedAlgorithms." Using macOS Transmit 5.8.2 as my client.

```
Connection from 192.168.1.XX port 51234 on 192.168.1.XX port 22 rdomain ""
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
userauth_pubkey: key type ssh-dss not in PubkeyAcceptedAlgorithms [preauth]
userauth_pubkey: key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]
userauth_pubkey: key type ssh-dss not in PubkeyAcceptedAlgorithms [preauth]
maximum authentication attempts exceeded for root from 192.168.1.XXport 51234 ssh2 [preauth]
Disconnecting authenticating user root 192.168.1.XX port 51234: Too many authentication failures [preauth]
```

Compared to successful command line SSH from the same computer:

```
Connection from 192.168.1.XX port 51487 on 192.168.1.XX port 22 rdomain ""
Accepted key RSA SHA256:XXXXXXX found at /etc/ssh/authorized_keys:1
Postponed publickey for root from 192.168.1.XX port 51487 ssh2 [preauth]
Accepted key RSA SHA256:XXXXXXX found at /etc/ssh/authorized_keys:1
Accepted publickey for root from 192.168.1.XX port 51487 ssh2: RSA SHA256: XXXXXXX
Starting session: shell on pts/0 for root from 192.168.1.XX port 51487 id 0
```

My config:

```
init_commands: []
packages: []
share_sessions: false
ssh:
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
  authorized_keys:
    - >-
      ssh-rsa
      XXXXX
    - >-
      ssh-rsa 
      XXXXX
  compatibility_mode: false
  password: ''
  sftp: true
  username: root
zsh: false

```
