### ISSUE TITLE
Running the command via does not work service: hassio.addon_stdin

### ISSUE THREAD

**Issue by DivanX10** [hassio-addons/addon-ssh#392]
# Problem/Motivation

> (Why the issue was filed)

HA core-2022.4.1
HA supervisor-2022.03.5
SSH & Web Terminal Current version: 10.1.1

Tell me, how can I run a command through the service? Previously, the option below worked, but now it has stopped working

1) If you run through the start of the service, then it does not work
```
service: hassio.addon_stdin
data:
  addon: a0d7b954_ssh
  input: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.enable
```

2) If you run it from the terminal itself, it works successfully

![image](https://user-images.githubusercontent.com/64090632/162547769-10195a4f-ba88-423e-a265-1317454cf52d.png)

## Expected behavior

> (What you expected to happen)

By starting the service, you can control the functions on the UPS

```
service: hassio.addon_stdin
data:
  addon: a0d7b954_ssh
  input: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.enable
```

For example, to turn on/off the sound on the UPS, I use this option

```
switch:
  - platform: template
    switches:
      ups_beeper:
        friendly_name: 'Beeper status'
        value_template: '{{ is_state("sensor.ups_beeper_status","enabled") }}'
        turn_on:
          service: hassio.addon_stdin
          data:
            addon: a0d7b954_ssh
            input: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.enable
        turn_off:
          service: hassio.addon_stdin
          data:
            addon: a0d7b954_ssh
            input: upscmd -u hassmon -p 12345678 ups@192.168.1.200:3493 beeper.disable
        icon_template: >-
          {% if is_state("sensor.ups_beeper_status","enabled") %}
            mdi:volume-high
          {% else %}
            mdi:volume-off
          {% endif %}
```

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
