### ISSUE TITLE
Couldn't connect to the ssh addon from network

### ISSUE THREAD

**Issue by Enzokot** [hassio-addons/addon-ssh#688]
# Problem/Motivation

Couldn't connect to the ssh addon (v.17.0.5) from network. After input login/password this error appears:
`sudo: unable to allocate pty: Read-only file system`

<details><summary>Logs from addon page</summary>

```
Connection from 192.168.217.50 port 57973 on 192.168.217.15 port 222 rdomain ""
Accepted password for hasshuser from 192.168.217.50 port 57973 ssh2
User child is on pid 410
Starting session: shell on pts/0 for hasshuser from 192.168.217.50 port 57973 id 0
/dev/pts/0: Permission denied
Close session: user hasshuser from 192.168.217.50 port 57973 id 0
Connection closed by 192.168.217.50 port 57973
Transferred: sent 3084, received 3324 bytes
Closing connection to 192.168.217.50 port 57973
```

</details>

## Expected behavior

Login addon without this error.

## Actual behavior

Login addon with this error.

## Steps to reproduce

Set up port, username, password and try connect to the addon with putty

<details><summary>My config for addon</summary>

```
ssh:
  username: hasshuser
  password: ""
  authorized_keys:
    - "!secret authorized_keys_ssh_addon"
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: false
share_sessions: true
packages:
  - p7zip
  - mc
init_commands: []
```

</details>
