### ISSUE TITLE
ssh logs me in as `root` despite username being set

### ISSUE THREAD

**Issue by flying-sheep** [hassio-addons/addon-ssh#704]
# Problem/Motivation

My config is

```yaml
username: xyz
password: ""
authorized_keys:
  - >-
    ssh-rsa
    ...
    phil@gnosis
```

When I log in via `ssh xyz@homeassistant`, I’m `root` and not `xyz`, so files I create are owned by `root` instead of that user.

## Expected behavior

I should become `xyz` on login

## Actual behavior

`whoami` tells me I’m `root`

## Steps to reproduce

Log in via public key with an username set

## Proposed changes

I should become the configured user. Maybe `sudo` should allow me to become root.
