### ISSUE TITLE
Documentation Update - Instructions for invoking ssh addon via Hassio panel

### ISSUE THREAD

**Issue by GaryOkie** [hassio-addons/addon-ssh#72]
# Problem/Motivation

This request is simply to update the documentation to explain how an Ingress-enabled addon can be invoked from the Hass.io panel.   

## Expected behavior
In particular, I am wanting to launch the latest v5 SSH addon from the Hassio 91.3 custom panel, but key parameters such as "url_path" and "ingress" are not known.   

Currently I am able to launch Configurator via custom panel, using the config below, but it took a lot of searching various threads and sifting through conflicting info to find out how.   Much better to just have it officially documented than ask the question in the forums and have the solution buried.

```
panel_custom:
  - name: hassio-main
    sidebar_title: ConfigEditor
    sidebar_icon: mdi:file-document-edit-outline
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: "core_configurator"
```
## Proposed changes

Now that addon-SSH supports Ingress and launches quite nicely from the "Launch Web UI" link, (THANK YOU!) it would be even nicer to document how addon-SSH (and possibly other addons) can be launched directly from the Hassio panel (saving time, clicks, and simplifying the UI).
