### ISSUE TITLE
SSH key - wont log in

### ISSUE THREAD

**Issue by jagauthier** [hassio-addons/addon-ssh#872]
What's the trick to getting a key to work?

```
ssh:
  username: hassio
  password: password
  authorized_keys:
    - >-
      ssh-rsa
      [key omitted]
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages: []
init_commands: []
```

Then using Putty, I've attached the key to the session. Prompted for password every time.
The contents of /root/.ssh/authorized_keys doesn't match the YAML, and I get this in the logs:

`Could not open user 'hassio' authorized keys '/root/.ssh/authorized_keys': Permission denied`
