### ISSUE TITLE
issue with kitty terminal

### ISSUE THREAD

**Issue by Solipsistmonkey** [hassio-addons/addon-ssh#901]
I was having some weird issues when trying to ssh in when using kitty. Granted, I only recently switched to using kitty from iTerm 2 recently so I'm still learning. But here's the result of me typing 'hello world'

![Image](https://github.com/user-attachments/assets/f492c599-043b-4d35-b14c-bf285d91e46c)

Following the advice from [kitty's FAQ](https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work) I tried both `kitten ssh hassio@ipaddress` and `infocmp -a xterm-kitty | ssh hassio@ipaddress tic -x -o \~/.terminfo /dev/stdin`  but still was having the issue.

I did manage to fix it myself but it was a bit of a roundabout way. 

I logged in through the webUI terminal and poked around a bit. Initially I was getting annoyed and confused because `ls -a' wasn't showing the `.terminfo` item (realized later it was a directory but wasn't sure at the time).

The webUI started me off in my home directory, so what gives? After a bit of scratching my head, I realized that `infocmp -a xterm-kitty | ssh hassio@ipaddress tic -x -o \~/.terminfo /dev/stdin` was creating that directory in the home dir for user `hassio` but ssh was logging me in as root. (I absolutely needed a lot more searching than the following screenshot 'cause I'm a dummy, it's just a recreation for brevity)

![Image](https://github.com/user-attachments/assets/df6fe2bc-9eb0-484c-a0ce-ab25b51a1b92)

Anyway, hoping to find a solution using a modified `infocmp -a xterm-kitty | ssh hassio@ipaddress tic -x -o \~/.terminfo /dev/stdin` command, I had permission issues.

<img width="1057" alt="Image" src="https://github.com/user-attachments/assets/cf3a3789-47b3-4563-9c6f-38e6330b2524" />

What ended up working for me was running `cp -R /home/hassio/.terminfo /root/` from the webUI. 

Maybe a note could be added about this in your installation instructions? I haven't looked much further than what I wrote here. So I don't know if this is an issue with homeassistant OS, your SSH addon or some other piece of the puzzle.

But either way, happy to have it working now and thanks for making this addon!

**Comment by Solipsistmonkey** [comment]
and I forgot that the addon is just a docker image. So no persistant changes like that would work. So what I ended up doing was...

On my machine:
`infocmp -a xterm-kitty | ssh hassio@ipaddress tic -x -o \~/.terminfo /dev/stdin`

Through the webUI:
`cp -R /home/hassio/.terminfo /share/`

and my config yaml:
```
ssh:
  username: hassio
  password: hunter2
  authorized_keys: []
  sftp: false
  compatibility_mode: false
  allow_agent_forwarding: false
  allow_remote_port_forwarding: false
  allow_tcp_forwarding: false
zsh: true
share_sessions: false
packages:
  - fish
  - shadow
  - ripgrep
init_commands:
  - /usr/bin/fish
  - cp /share/.terminfo /root -R
  - chsh $(whoami) -s fish
  - mkdir -p /root/.config/fish/completions/
  - /usr/bin/ha completion fish > /root/.config/fish/completions/ha.fish
```
